name: test suite
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build and Check
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          components: clippy, rustfmt
      - uses: wild-linker/action@0bbbfa5df4380cab8e63cb8505a1ce65e1d10203 # 0.9.0
      - name: Build and test
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy -- -Dwarnings
