name: test suite
on:
  pull_request:

jobs:
  test:
    name: Build and Check
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          components: clippy, rustfmt
      - uses: wild-linker/action@0bbbfa5df4380cab8e63cb8505a1ce65e1d10203 # 0.9.0
      - name: Build and test
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy -- -Dwarnings
