name: test suite
on:
  pull_request:

jobs:
  test:
    name: Build and Check
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
        with:
          components: clippy, rustfmt
      - uses: wild-linker/action@dc926c45399e1842cf81e604f52bdf0ad86a0c09 # v0.10.0
      - name: Build and test
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy -- -Dwarnings
